"""AI insight endpoints."""

from __future__ import annotations

import logging

from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session

from app.database import get_db
from app.deps import get_current_user, not_found
from app.models import User
from app.schemas.analytics import InsightGenerateResponse, InsightOut
from app.schemas.common import Message
from app.services import insight_service

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/insights", tags=["Insights"])


@router.get(
    "",
    response_model=list[InsightOut],
    summary="List insights",
    description=(
        "Returns previously generated insights. Each carries the structured data "
        "the figures were derived from, plus an optional AI-written explanation."
    ),
)
def list_insights(
    include_dismissed: bool = False,
    limit: int = Query(default=30, ge=1, le=100),
    user: User = Depends(get_current_user),
    session: Session = Depends(get_db),
) -> list[InsightOut]:
    return [
        InsightOut.model_validate(i)
        for i in insight_service.list_insights(session, user, include_dismissed, limit)
    ]


@router.post(
    "/generate",
    response_model=InsightGenerateResponse,
    summary="Regenerate insights",
    description=(
        "Runs every detector (budget risk, unusual transactions, category changes, "
        "savings opportunities, goal pace, cash-flow risk, savings rate, recurring "
        "charges). All figures are computed by the backend; the AI layer, if "
        "configured, only rewrites the wording. Existing findings are refreshed in "
        "place rather than duplicated."
    ),
)
def generate(
    user: User = Depends(get_current_user), session: Session = Depends(get_db)
) -> InsightGenerateResponse:
    insights, ai_used = insight_service.generate_insights(session, user)
    session.commit()

    note = None
    if not insights:
        note = (
            "No insights yet - Finora needs some transaction history before it can "
            "find patterns. Add a few transactions or load the demo data."
        )
    elif not ai_used:
        note = (
            "Insights were generated by Finora's deterministic analysis engine. "
            "Configure AI_API_KEY for conversational explanations; the figures are "
            "identical either way."
        )

    return InsightGenerateResponse(
        generated=len(insights),
        insights=[InsightOut.model_validate(i) for i in insights],
        ai_enabled=ai_used,
        note=note,
    )


@router.post("/{insight_id}/read", response_model=InsightOut, summary="Mark an insight as read")
def mark_read(
    insight_id: str,
    user: User = Depends(get_current_user),
    session: Session = Depends(get_db),
) -> InsightOut:
    insight = insight_service.get_insight(session, user, insight_id)
    if insight is None:
        raise not_found("Insight")
    updated = insight_service.mark_read(session, insight)
    session.commit()
    session.refresh(updated)
    return InsightOut.model_validate(updated)


@router.post("/{insight_id}/dismiss", response_model=Message, summary="Dismiss an insight")
def dismiss(
    insight_id: str,
    user: User = Depends(get_current_user),
    session: Session = Depends(get_db),
) -> Message:
    insight = insight_service.get_insight(session, user, insight_id)
    if insight is None:
        raise not_found("Insight")
    insight_service.dismiss(session, insight)
    session.commit()
    return Message(detail="Insight dismissed")
