"""initial schema

Revision ID: da6313565dfc
Revises: 
Create Date: 2026-09-28 18:07:21.182378
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'da6313565dfc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('monthly_income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('income_source', sa.String(length=80), nullable=True),
    sa.Column('typical_monthly_expenses', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('savings_goal_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('emergency_fund_target', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('budgeting_preference', sa.Enum('STRICT', 'BALANCED', 'FLEXIBLE', name='budgetingpreference', native_enum=False, length=20), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('reset_token_hash', sa.String(length=128), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_reset_token_hash'), ['reset_token_hash'], unique=False)

    op.create_table('ai_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_conversations_user_updated', ['user_id', 'updated_at'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('total_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_month', name='uq_budget_user_period')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_period_month'), ['period_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_budgets_user_period', ['user_id', 'period_month'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.Enum('INCOME', 'EXPENSE', 'BOTH', name='categorykind', native_enum=False, length=10), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_category_user_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_categories_user_kind', ['user_id', 'kind'], unique=False)

    op.create_table('financial_goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('goal_type', sa.String(length=40), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ACHIEVED', 'PAUSED', 'ARCHIVED', name='goalstatus', native_enum=False, length=10), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_goals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_goals_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_goals_user_status', ['user_id', 'status'], unique=False)

    op.create_table('insights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('SPENDING_INCREASE', 'SPENDING_DECREASE', 'BUDGET_RISK', 'BUDGET_EXCEEDED', 'ANOMALY', 'RECURRING_EXPENSE', 'SAVINGS_OPPORTUNITY', 'SAVINGS_RATE', 'GOAL_PROGRESS', 'CASHFLOW_RISK', 'NEW_MERCHANT', name='insighttype', native_enum=False, length=30), nullable=False),
    sa.Column('severity', sa.Enum('POSITIVE', 'INFO', 'WARNING', 'CRITICAL', name='insightseverity', native_enum=False, length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('fingerprint', sa.String(length=120), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insights_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_insights_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index('ix_insights_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_insights_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_insights_user_type', ['user_id', 'type'], unique=False)

    op.create_table('ai_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole', native_enum=False, length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tools_used', sa.JSON(), nullable=True),
    sa.Column('retrieved_facts', sa.JSON(), nullable=True),
    sa.Column('generation_mode', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_messages_conversation_created', ['conversation_id', 'created_at'], unique=False)

    op.create_table('budget_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('budget_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recommended_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('recommendation_basis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'category_id', name='uq_budget_item_category')
    )
    with op.batch_alter_table('budget_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_items_budget_id'), ['budget_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_items_created_at'), ['created_at'], unique=False)

    op.create_table('goal_contributions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['financial_goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal_contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_contributions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_contributions_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_contributions_occurred_on'), ['occurred_on'], unique=False)

    op.create_table('receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PROCESSED', 'FAILED', 'CONFIRMED', name='receiptstatus', native_enum=False, length=12), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('ocr_engine', sa.String(length=40), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('merchant', sa.String(length=160), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('suggested_category_id', sa.String(length=36), nullable=True),
    sa.Column('field_confidence', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['suggested_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_user_id'), ['user_id'], unique=False)

    op.create_table('receipt_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('receipt_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipt_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipt_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipt_items_receipt_id'), ['receipt_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('receipt_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', name='transactiontype', native_enum=False, length=10), nullable=False),
    sa.Column('merchant', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'RECEIPT', 'SEED', 'IMPORT', name='transactionsource', native_enum=False, length=10), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('ai_categorized', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('anomaly_status', sa.Enum('NONE', 'FLAGGED', 'CONFIRMED', 'EXPECTED', 'IGNORED', name='anomalystatus', native_enum=False, length=12), nullable=False),
    sa.Column('anomaly_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_anomaly_status'), ['anomaly_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_occurred_on'), ['occurred_on'], unique=False)
        batch_op.create_index('ix_transactions_user_category_date', ['user_id', 'category_id', 'occurred_on'], unique=False)
        batch_op.create_index('ix_transactions_user_date', ['user_id', 'occurred_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_transactions_user_merchant', ['user_id', 'merchant'], unique=False)
        batch_op.create_index('ix_transactions_user_type_date', ['user_id', 'type', 'occurred_on'], unique=False)

    op.create_table('ml_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('model_name', sa.String(length=60), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('input_document', sa.Text(), nullable=True),
    sa.Column('input_description', sa.Text(), nullable=True),
    sa.Column('input_merchant', sa.String(length=160), nullable=True),
    sa.Column('input_payment_method', sa.String(length=40), nullable=True),
    sa.Column('input_transaction_type', sa.String(length=10), nullable=True),
    sa.Column('predicted_category', sa.String(length=60), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('alternatives', sa.JSON(), nullable=True),
    sa.Column('final_category', sa.String(length=60), nullable=True),
    sa.Column('was_corrected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_predictions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_predictions_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_predictions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_predictions_model', ['model_name', 'model_version'], unique=False)
        batch_op.create_index('ix_predictions_user_corrected', ['user_id', 'was_corrected'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_predictions_user_corrected')
        batch_op.drop_index('ix_predictions_model')
        batch_op.drop_index(batch_op.f('ix_ml_predictions_user_id'))
        batch_op.drop_index(batch_op.f('ix_ml_predictions_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ml_predictions_created_at'))

    op.drop_table('ml_predictions')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_user_type_date')
        batch_op.drop_index('ix_transactions_user_merchant')
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index('ix_transactions_user_date')
        batch_op.drop_index('ix_transactions_user_category_date')
        batch_op.drop_index(batch_op.f('ix_transactions_occurred_on'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_category_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_anomaly_status'))

    op.drop_table('transactions')
    with op.batch_alter_table('receipt_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_items_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_receipt_items_created_at'))

    op.drop_table('receipt_items')
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_user_id'))
        batch_op.drop_index(batch_op.f('ix_receipts_status'))
        batch_op.drop_index(batch_op.f('ix_receipts_created_at'))

    op.drop_table('receipts')
    with op.batch_alter_table('goal_contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_contributions_occurred_on'))
        batch_op.drop_index(batch_op.f('ix_goal_contributions_goal_id'))
        batch_op.drop_index(batch_op.f('ix_goal_contributions_created_at'))

    op.drop_table('goal_contributions')
    with op.batch_alter_table('budget_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_items_created_at'))
        batch_op.drop_index(batch_op.f('ix_budget_items_category_id'))
        batch_op.drop_index(batch_op.f('ix_budget_items_budget_id'))

    op.drop_table('budget_items')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_conversation_created')
        batch_op.drop_index(batch_op.f('ix_ai_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_messages_conversation_id'))

    op.drop_table('ai_messages')
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.drop_index('ix_insights_user_type')
        batch_op.drop_index(batch_op.f('ix_insights_user_id'))
        batch_op.drop_index('ix_insights_user_created')
        batch_op.drop_index(batch_op.f('ix_insights_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_insights_created_at'))

    op.drop_table('insights')
    with op.batch_alter_table('financial_goals', schema=None) as batch_op:
        batch_op.drop_index('ix_goals_user_status')
        batch_op.drop_index(batch_op.f('ix_financial_goals_user_id'))
        batch_op.drop_index(batch_op.f('ix_financial_goals_created_at'))

    op.drop_table('financial_goals')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('ix_categories_user_kind')
        batch_op.drop_index(batch_op.f('ix_categories_user_id'))
        batch_op.drop_index(batch_op.f('ix_categories_created_at'))

    op.drop_table('categories')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index('ix_budgets_user_period')
        batch_op.drop_index(batch_op.f('ix_budgets_user_id'))
        batch_op.drop_index(batch_op.f('ix_budgets_period_month'))
        batch_op.drop_index(batch_op.f('ix_budgets_created_at'))

    op.drop_table('budgets')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversations_user_updated')
        batch_op.drop_index(batch_op.f('ix_ai_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_created_at'))

    op.drop_table('ai_conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_reset_token_hash'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    # ### end Alembic commands ###
